# Generated by Django 3.0.2 on 2021-10-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('es', 'es'), ('en', 'en')], default='es', max_length=30),
        ),
    ]
