# Generated by Django 3.0.2 on 2022-01-10 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0002_campaign_claim_claimstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimstatus',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together={('user', 'campaign')},
        ),
    ]
