# Generated by Django 3.0.2 on 2020-06-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('logged', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('button_id', models.CharField(default='', max_length=200)),
                ('component_id', models.CharField(default='', max_length=200)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('event_id', models.CharField(default='', max_length=200)),
                ('fired_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
