# Generated by Django 3.0.2 on 2020-09-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'verbose_name': 'Login history', 'verbose_name_plural': 'Login history'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Logs', 'verbose_name_plural': 'Logs'},
        ),
    ]
