# Generated by Django 3.0.2 on 2020-09-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Terms and conditions', 'verbose_name_plural': 'Terms and conditions'},
        ),
    ]
