# Generated by Django 3.0.2 on 2022-05-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_investorcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_questions', to='surveys.Question')),
            ],
            options={
                'verbose_name': 'translated_question',
                'verbose_name_plural': 'translated_questions',
            },
        ),
        migrations.CreateModel(
            name='ChoiceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=2)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_choices', to='surveys.Choice')),
            ],
            options={
                'verbose_name': 'translated_choice',
                'verbose_name_plural': 'translated_choices',
            },
        ),
    ]
