# Generated by Django 3.0.2 on 2021-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=15, max_digits=30)),
                ('type', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
            ],
        ),
    ]
