# Generated by Django 3.0.2 on 2021-07-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0003_auto_20210707_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='subscription_plans.PlanModel'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
