# Generated by Django 3.0.2 on 2021-07-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0004_auto_20210708_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscriptionmodel',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription_plans.PlanModel'),
        ),
    ]
