# Generated by Django 3.0.2 on 2021-07-19 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0005_auto_20210708_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('payment_link', models.CharField(max_length=1000)),
                ('provider_plan_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='planmodel',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planmodel',
            name='frequency_type',
            field=models.CharField(choices=[('months', 'months'), ('years', 'years')], default='months', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='currency',
            field=models.CharField(default='ARS', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 19, 10, 36, 767528)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 19, 10, 43, 904824)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=15, max_digits=30)),
                ('currency', models.CharField(max_length=15)),
                ('plan_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription_plans.PlanSubscriptionModel')),
            ],
        ),
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subscription_plans.PaymentMethodModel'),
        ),
    ]
