# Generated by Django 3.0.2 on 2021-07-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0006_auto_20210719_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscriptionmodel',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription_plans.PaymentMethodModel'),
        ),
    ]
