# Generated by Django 3.0.2 on 2021-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0007_auto_20210719_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscriptionmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
