# Generated by Django 3.0.2 on 2021-07-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0008_auto_20210723_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscriptionmodel',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscription_plans.PaymentMethodModel'),
        ),
    ]
