# Generated by Django 3.0.2 on 2021-07-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0008_paymentmodel_plan_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subscription_plans.PaymentMethodModel'),
            preserve_default=False,
        ),
    ]
