# Generated by Django 3.0.2 on 2021-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0009_auto_20210723_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('authorized', 'authorized')], default='pending', max_length=150),
            preserve_default=False,
        ),
    ]
