# Generated by Django 3.0.2 on 2021-07-16 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0009_plansubscriptionmodel_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 13, 9, 0, 795478)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 13, 9, 11, 142968)),
            preserve_default=False,
        ),
    ]
