# Generated by Django 3.0.2 on 2021-07-28 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription_plans', '0010_plansubscriptionmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscriptionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
