# Generated by Django 3.0.2 on 2021-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0010_auto_20210716_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='currency',
            field=models.CharField(default='ARS', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansubscriptionmodel',
            name='frequency_type',
            field=models.CharField(choices=[('months', 'months'), ('years', 'years')], default='months', max_length=100),
            preserve_default=False,
        ),
    ]
