# Generated by Django 3.0.2 on 2021-08-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0011_auto_20210728_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
