# Generated by Django 3.0.2 on 2021-08-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0012_paymentmethodmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='state',
        ),
    ]
